### ISSUE TITLE
Model Editor doesn't have access to configuration files stored in cloud 

### ISSUE THREAD

**Issue by NRCgg** [NRC-Research/SNAP-issues#31]
When a user's site_config.prop file references a storage location in the cloud, SNAP should prompt the user to authenticate with an associated account so that SNAP can retrieve the needed data.   Instead, when trying to run SNAP on my GFE-laptop, I get the following error message on startup:

![image](https://user-images.githubusercontent.com/56318952/174796466-7cb2f4f4-239a-4f16-bece-e91416b320f0.png)

 
Note that on the same GFE-laptop SNAP setup, when I go into locate applications on the cloud, *it does* perform the authentication as expected.

**Comment by dul-apt** [comment]
This issue is a result of the default AWS configuration not specifying an appropriate default region. It can be addressed by using a query string identifying the s3 file region in the global configuration URI (property site_config in the <SNAP INSTALL DIR>/config/site_config.prop file). The following is an example of a correction used:

Invalid site_config.prop file contained: site_config=s3://hpcs-snap-codes/global_site_config-windows.xml

Corrected site_config.prop file now contains: site_config=s3://hpcs-snap-codes/global_site_config-windows.xml?region=us-gov-east-1

This issue was not encountered on RESGC instances because the region information is part of the default configuration.

**Comment by dul-apt** [comment]
This issue is a result of the default AWS configuration not specifying an appropriate default region. It can be addressed by using a query string identifying the s3 file region in the global configuration URI (property site_config in the /config/site_config.prop file). The following is an example of a correction used:

Invalid site_config.prop file contained: site_config=s3://hpcs-snap-codes/global_site_config-windows.xml

Corrected site_config.prop file now contains: site_config=s3://hpcs-snap-codes/global_site_config-windows.xml?region=us-gov-east-1

This issue was not encountered on RESGC instances because the region information is part of the default configuration.
