### ISSUE TITLE
MELCOR Models in SNAP - enhancements related to interactive functions in MELCOR 1.8.6 and MELCOR 2.x

### ISSUE THREAD

**Issue by evgeni-borisov** [NRC-Research/SNAP-issues#51]
Hello!
I would like to propose the following functionalities for the MELCOR code application within the SNAP environment:

1. The availability of the "extend" option when initiating a restart calculation via the SNAP Job Stream. Currently, SNAP defaults to using the "override" option for restarts. Although there is guidance from Bill Dunsford for manually setting the "extend" option, we are currently facing challenges in successfully implementing it. (we probably miss something)  We will make additional attempts, and if we succeed, we will post detailed information. 

2. The ability to invoke the MELCOR interactive menu within SNAP (if not already available through commands), which is typically done in a DOS window by pressing ESC and initiating the command "hello!". Then plenty of interactive options are available. 

Best regards,
Evgeni

**Comment by WDunsford** [comment]
Added in MELCOR plug-in version 2.8.3, released 12/15/2023

**Comment by evgeni-borisov** [comment]
Hello, Bill! How can I check the new features implemented since MELCOR plug-in version 2.8.3, released on 12/15/2023? I haven't noticed any differences. Were all the suggestions addressed in this update?

**Comment by evgeni-borisov** [comment]
Hello, Bill! 
I have successfully extended a calculation in SNAP after your updates :). 
How can I check the following features implemented since MELCOR plug-in version 2.8.3, released on 12/15/2023? 
1. Invoking the "hello!" option
2. Invoking the "exit!" option

**Comment by WDunsford** [comment]
Hi Evgeni,

The interactive commands through standard application input are only available when you run the MELCOR code manually, not through the SNAP calculation sever.  The SNAP calculation server has a different way of interacting with MELCOR, through animation models and interactive commands through the Job Status.

I'm about to be out of the office on vacation but you should be aware that we've released 7 versions of the MELCOR plug-in since 2.8.3. Our current version is 3.0.0 which was released 10 days ago. We're currently implementing the ASCII context capability for the RN package.

Regards,


Bill Dunsford

Software Architect, Energy, Space, and Waste

Information Systems Laboratories, Inc.

575 Montour Blvd, Suite 3

Bloomsburg, PA 17815

Phone: (703) 269-3614

Email: ***@***.***

www.ISLinc.com<http://www.islinc.com/>

________________________________

**Comment by evgeni-borisov** [comment]
Hi, Bill,

I’m using the latest SNAP release with the corresponding plug-ins. I understand that the hello! and exit! commands are available in MELCOR's standard terminal mode, but as far as I understand, they cannot be invoked through SNAP. That was my main question.

Additionally, is there an option within SNAP to terminate a calculation and create a restart point at the moment of termination? 

Additionally, the Pause interactive command is actually not working for my SNAP installation when working with MELCOR.
