### ISSUE TITLE
SNAP 4.1.4: issue with the TRACE plugin when using LUA scripting with patch-8 model

### ISSUE THREAD

**Issue by fmax85** [NRC-Research/SNAP-issues#65]
Good morning,

I noticed an issue concerning the SNAP support to embed LUA scripting in TRACE patch-8 models. Below, I attach some figures of the input deck of the same sample test: on the left is the working model (drafted with a text editor), on the right is the input model generated with SNAP.
- The first figure shows the actual LUA code entered in the "Embedded LUA" entry in the "Model Options" section of the model. This is working fine in SNAP.
- The current TRACE plugin does not contain the "hasluahooks" variable among the available Namelist variables (second figure). Please, enable this selection.
- The current TRACE plugin does not allow the possibility to enter the parameters for the actual LUA hook, i.e. the correlation function to call, its type, the targeted component, etc. (third figure). Please, enable this selection (possibly in the "Model Options" section).

Thank you in advance!
--
Fabio

![snap_lua_3](https://github.com/NRC-Research/SNAP-issues/assets/38402370/0e855753-c746-445c-9944-c5971fd321da)
![snap_lua_1](https://github.com/NRC-Research/SNAP-issues/assets/38402370/f9a5ab18-cd12-46c2-841e-5fd3c870e0e2)
![snap_lua_2](https://github.com/NRC-Research/SNAP-issues/assets/38402370/00826463-1fcd-433c-b3a4-c559948c29c0)

**Comment by NRCgg** [comment]
@fmax85 Thanks for the report!  Can you please give this a try with the new SNAP 4.2.0 distribution as well?  

Thanks in advance!

**Comment by fmax85** [comment]
Sure, I will update SNAP today and try with the new version

**Comment by NRCgg** [comment]
@fmax85 I discussed this problem further with @dul-isl and learned that there was a misunderstanding about how the LUA scripts would be added.  This will be fixed in the next SNAP-TRACE plugin version.  

I am leaving this issue open until it is confirmed that the next release fixes this issue.
<details><summary>Details</summary>
<p>

[Reference Notes from ISL-NRC meeting regarding this issue.](https://github.com/NRC-Research/SNAP-contract-notes/blob/main/development-contract-notes/Meeting-notes/20231115-biweekly.md)

</p>
</details>

**Comment by WDunsford** [comment]
This has been resolved in TRACE Plug-in version 4.6.2 released 12-19-2023
