### ISSUE TITLE
Violation of GNU GPL Open Source License: AptPlot source code not published!

### ISSUE THREAD

**Issue by eGit** [NRC-Research/SNAP-issues#71]
With AptPlot 8.0 it was merged into the SNAP software. The last standalone Open Source Aptplot was: 7.0.2.

The source code was never published and the developer refused providing the source code when asked. This is all in severe violation of the GPL license! If you publish the binary, you have to provide the source code!

Please provide the source code!

![Screenshot 2021-12-07 at 00-35-45 AptPlot License](https://github.com/NRC-Research/SNAP-issues/assets/842855/10e34d18-eb21-48ad-a753-8180dded5458)

**Comment by dbarber-islinc** [comment]
The poster correctly observes that AptPlot 8.0 was merged into SNAP and that the source code is not available to the public.  The poster also claims that the failure to provide the source code is a “severe violation of the GPL license!  If you publish the binary, you have to provide the source code!”  The poster is flatly wrong.

The current version of AptPlot is 8.0.3, and it is distributed under ISL's End User License Agreement (EULA); it is no longer governed by the GPL.  ISL will never provide the source code for its wholly owned intellectual property, unless it has determined that doing so is in the best interests of the Corporation and its Stockholders.  ISL has not determined to make AptPlot 8.0.3 open source, and it has no present design to do so.  ISL consequently will not supply the source code as the poster requests.

The poster also observes that AptPlot 7.0.2 was open source.  The poster is correct.  AptPlot 7.0.2 was devised by Applied Programming Technologies (APT) and it determined to make the source code for AptPlot 7.0.2 open source.  ISL acquired the assets of APT, including AptPlot 7.0.2, but nothing in APT’s end user license agreement (EULAs) or the terms of the acquisition either obligated ISL to continue producing open-source software or to continue offering open-source versions, such as AptPlot 7.0.2.  No other contract requirement, moreover, or source of positive law, such as a statute, requires ISL to do so.  ISL consequently elected to improve AptPlot, redesign its source code, and issue it as a new version.  AptPlot 7.0.2 is no longer made available because it has been superseded, and ISL no longer supports the software.

The poster asserts without any support or proof that ISL failed to respond to a request for the open-source code.  ISL has scoured its contemporaneous and detailed records concerning requests for support, and it has found no request for the source code for AptPlot, either version 7.0.2 or version 8.0.3.  The poster's claim is accordingly baseless and meritless, even if such a claim mattered in the least, which the law definitively declares does not.

**Comment by dbarber-islinc** [comment]
AptPlot 7.0.2 is no longer supported or available.  We are not able to provide source code and are under no obligation to do so.

**Comment by eGit** [comment]
That request was made on Dec. 6th 2021 to support@appliedprog.com

Since the binary of  AptPlot 7.0.2 was published and distributed under the GPL you (the rightful owner of Applied Programming Technologies (APT)) has to make the source code for AptPlot 7.0.2 available - especially upon request.

Somebody downloading the binary for AptPlot 7.0.2 published under the GPL is assured by the license, that the source code is available. Somebody broke that promise of the GPL by not providing the source code upon request. I don't want to speculate but it must have happened around the time of the aquisition of APT by ISL? So you think it is not your responsibility?

**Comment by dbarber-islinc** [comment]
Poster asserts that it made the request for source code to APT on December 6, 2021.  Today’s date is February 13, 2024, more than two years after Poster claims it made a request for the source code to APT.  ISL observes that two years is a long time to wait to complain about a matter that Poster asserts is of such grave importance.  No matter.  Poster admits it made its request to APT.  ISL acquired APT’s assets long after December 6, 2021, the date on which Poster asserts it requested the source code from APT.  ISL acquired no duties or liabilities in its acquisition of APT’s assets.  APT retained both.  Poster’s dispute, if any can be recognized, resides with APT and APT alone.  ISL will never supply source code to its intellectual property, except when it determines doing so is in the Corporation’s interests, its Stockholders interests, or both.  No such determination applies here and no source code will be supplied.  The Poster may address any further complaints to APT.  ISL will have no further response to comments and considers this matter closed.
